/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import java.awt.Color;
import java.awt.Component;

/**
 *
 * @author 91799
 */
public class StudentDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashboard
     */
   Color DefaultColor,ClickedColor;
    public StudentDashboard(){
        initComponents();
        DefaultColor= new Color(204,204,255);
        ClickedColor = new Color(246,208,129);
        
        // set default color 
        
         viewnotice.setBackground(DefaultColor);
         enrollnotice.setBackground(DefaultColor);
         
         //ready.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        viewnotice = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        viewnotice1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        viewnotice2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        viewnotice3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enrollnotice = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JOptionPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Student Dashboard ");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 300, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 80));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewnotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewnoticeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewnoticeMousePressed(evt);
            }
        });
        viewnotice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("ViewNotice");
        viewnotice.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 120, 39));

        viewnotice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewnotice1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewnotice1MousePressed(evt);
            }
        });
        viewnotice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("ViewNotice");
        viewnotice1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, 39));

        viewnotice.add(viewnotice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 50));

        viewnotice2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewnotice2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewnotice2MousePressed(evt);
            }
        });
        viewnotice2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("ViewNotice");
        viewnotice2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 120, 39));

        viewnotice3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewnotice3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewnotice3MousePressed(evt);
            }
        });
        viewnotice3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("ViewNotice");
        viewnotice3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, 39));

        viewnotice2.add(viewnotice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 50));

        viewnotice.add(viewnotice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 50));

        jPanel5.add(viewnotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/resize-1696465088436896598studentlogovector.jpg"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, 100));

        enrollnotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enrollnoticeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enrollnoticeMousePressed(evt);
            }
        });
        enrollnotice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("workshop");
        enrollnotice.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 6, 119, 30));

        jPanel5.add(enrollnotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, 50));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 430));

        javax.swing.GroupLayout JOptionPanel1Layout = new javax.swing.GroupLayout(JOptionPanel1);
        JOptionPanel1.setLayout(JOptionPanel1Layout);
        JOptionPanel1Layout.setHorizontalGroup(
            JOptionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        JOptionPanel1Layout.setVerticalGroup(
            JOptionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel3.add(JOptionPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 680, 430));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewnoticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewnoticeMouseClicked
        // TODO add your handling code here:
         Studentnotice1 upsa= new Studentnotice1();
          JOptionPanel1.add(upsa);//setVisible(true);
        upsa.setVisible(true);
        
     
    }//GEN-LAST:event_viewnoticeMouseClicked

    private void viewnoticeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewnoticeMousePressed
        // TODO add your handling code here:
          viewnotice.setBackground(ClickedColor);
          enrollnotice.setBackground(DefaultColor);

    }//GEN-LAST:event_viewnoticeMousePressed

    private void viewnotice1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewnotice1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewnotice1MouseClicked

    private void viewnotice1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewnotice1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewnotice1MousePressed

    private void viewnotice3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewnotice3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewnotice3MouseClicked

    private void viewnotice3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewnotice3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewnotice3MousePressed

    private void viewnotice2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewnotice2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewnotice2MouseClicked

    private void viewnotice2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewnotice2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewnotice2MousePressed

    private void enrollnoticeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollnoticeMousePressed
        // TODO add your handling code here:viewnotice.setBackground(ClickedColor);
        viewnotice.setBackground(DefaultColor);
          enrollnotice.setBackground(ClickedColor);
    }//GEN-LAST:event_enrollnoticeMousePressed

    private void enrollnoticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollnoticeMouseClicked
        // TODO add your handling code here:
        ButtonInTable ups= new  ButtonInTable();
       Component add = JOptionPanel1.add(ups); //setVisible(true);
        ups.setVisible(true);
       
       // new code
     /*  DisplayDatabaseTable ups= new DisplayDatabaseTable();
          JOptionPanel1.add(ups);//setVisible(true);
        ups.setVisible(true)*/
    }//GEN-LAST:event_enrollnoticeMouseClicked
  


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
             });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JOptionPanel1;
    private javax.swing.JPanel enrollnotice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel viewnotice;
    private javax.swing.JPanel viewnotice1;
    private javax.swing.JPanel viewnotice2;
    private javax.swing.JPanel viewnotice3;
    // End of variables declaration//GEN-END:variables

}
