/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import java.awt.Color;

/**
 *
 * @author 91799
 */
public class StudentDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashboard
     */
   Color DefaultColor,ClickedColor;
    public StudentDashboard(){
        initComponents();
        DefaultColor= new Color(204,204,255);
        ClickedColor = new Color(246,208,129);
        
        // set default color 
         viewnotice.setBackground(DefaultColor);
         enrollnotice.setBackground(DefaultColor);
         
         //ready.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        viewnotice = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enrollnotice = new javax.swing.JButton();
        JOptionPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 80));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewnotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewnoticeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewnoticeMousePressed(evt);
            }
        });
        viewnotice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ViewNotice");
        viewnotice.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 84, 39));

        jPanel5.add(viewnotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 40));

        enrollnotice.setText("Workshop");
        enrollnotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollnoticeActionPerformed(evt);
            }
        });
        jPanel5.add(enrollnotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, 50));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 430));

        javax.swing.GroupLayout JOptionPanel1Layout = new javax.swing.GroupLayout(JOptionPanel1);
        JOptionPanel1.setLayout(JOptionPanel1Layout);
        JOptionPanel1Layout.setHorizontalGroup(
            JOptionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        JOptionPanel1Layout.setVerticalGroup(
            JOptionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel3.add(JOptionPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 680, 430));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewnoticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewnoticeMouseClicked
        // TODO add your handling code here:
         Studentnotice1 upsa= new Studentnotice1();
          JOptionPanel1.add(upsa);//setVisible(true);
        upsa.setVisible(true);
        
     
    }//GEN-LAST:event_viewnoticeMouseClicked

    private void viewnoticeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewnoticeMousePressed
        // TODO add your handling code here:
          viewnotice.setBackground(ClickedColor);
          enrollnotice.setBackground(DefaultColor);

    }//GEN-LAST:event_viewnoticeMousePressed
private void openButtonInTable1() {
    ButtonInTable1 buttonInTable1 = new ButtonInTable1();
    buttonInTable1.setLocationRelativeTo(this); // Center the new frame relative to StudentDashboard
    buttonInTable1.setVisible(true);
}
    private void enrollnoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollnoticeActionPerformed
        // TODO add your handling code here:
     //   dispose();
      /*  ButtonInTable1 r = new ButtonInTable1();
        r.setTitle("enroll in  workshop  ");
        r.setLocationRelativeTo(null);
        r.setVisible(true);*/
       openButtonInTable1();
    }//GEN-LAST:event_enrollnoticeActionPerformed
  


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
             });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JOptionPanel1;
    private javax.swing.JButton enrollnotice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel viewnotice;
    // End of variables declaration//GEN-END:variables

}
